server:
  port: ${SERVER_PORT}
  read_timeout: 10000
  read_header_timeout: 2000
common:
  log:
    level: "DEBUG"
    flush_time: 5
    run_writer:
      file_path: "../log/run/run.log"
      max_size: 100
      max_age: 7
      max_backups: 15
      local_time: true
      compress: false
      std_print: true
  infra:
    auth:
      secret_key: "~&bBD(92$8~JE^XZ"
      expire_time: 300
    mysql:
      host: "${MYSQL_HOST}"
      port: ${MYSQL_PORT}
      username: "${MYSQL_USERNAME}"
      password: "${MYSQL_PASSWORD}"
      db_name: "${MYSQL_DB_NAME}"
    mq:
      address: "${MQ_ADDR}"
      expire: 10
    oss:
      id: "LTAI5tFnKogF9bTcvoJxrZor"
      secret: "W1veUccsXDy3mciIzAnNF1IpJ0u0CG"
      endpoint: "oss-cn-shanghai.aliyuncs.com"
      bucket: "victor-bucket"
      root_dir: "project/vicblog"
      picture_folder_name: "user_photo"
    audit:
      addr: "${AUDIT_ADDR}"
      expire_time: 10
blog:
  blog_info:
    logo: "https://img.quanxiaoha.com/quanxiaoha/f97361c0429d4bb1bc276ab835843065.jpg"
    name: "vicblog"
    author: "victor"
    introduction: "这是一段介绍"
    avatar: "https://img.quanxiaoha.com/quanxiaoha/f97361c0429d4bb1bc276ab835843065.jpg"
    github_homepage: "https://github.com/victorzhou123"
    gitee_homepage: "https://github.com/victorzhou123"
    csdn_homepage: "https://github.com/victorzhou123"
    zhihu_homepage: "https://github.com/victorzhou123"
comment:
  qq_info:
    url: "https://api.qjqq.cn/api/qqinfo"
