basePath: /api
definitions:
  app.ArticleListDto:
    properties:
      cover:
        type: string
      createTime:
        type: string
      id:
        type: integer
      isPublish:
        type: boolean
      isTop:
        type: boolean
      title:
        type: string
    type: object
  app.UserAndTokenDto:
    properties:
      email:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  controller.reqCategory:
    properties:
      name:
        type: string
    type: object
  controller.reqLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  controller.reqTag:
    properties:
      names:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: victorzhoux@163.com
    name: VictorZhou
  title: vicBlog server API
  version: "1.0"
paths:
  /v1/admin/article/{id}:
    delete:
      description: delete one article of request user
      parameters:
      - description: article ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: delete article
      tags:
      - Article
  /v1/admin/article/list:
    post:
      consumes:
      - application/json
      description: list all articles of request user
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/app.ArticleListDto'
            type: array
      summary: List articles
      tags:
      - Article
  /v1/admin/category:
    get:
      consumes:
      - application/json
      description: list category with pagination
      parameters:
      - description: current page of user queried
        in: query
        name: current
        required: true
        type: integer
      - description: single page size of user queried
        in: query
        name: size
        required: true
        type: integer
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/app.ArticleListDto'
            type: array
      summary: List category
      tags:
      - Category
    post:
      consumes:
      - application/json
      description: add a category item
      parameters:
      - description: body of add category
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqCategory'
      responses: {}
      summary: Add category
      tags:
      - Category
  /v1/admin/category/{id}:
    delete:
      consumes:
      - application/json
      description: delete one category
      parameters:
      - description: id of category, which user want to delete
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      summary: Delete category
      tags:
      - Category
  /v1/admin/tag:
    delete:
      consumes:
      - application/json
      description: delete a tag item
      parameters:
      - description: body of add tag
        in: body
        name: path
        required: true
        schema:
          $ref: '#/definitions/controller.reqTag'
      responses:
        "200":
          description: OK
      summary: Delete tag
      tags:
      - Tag
    post:
      consumes:
      - application/json
      description: add a tag item
      parameters:
      - description: body of add tag
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqTag'
      responses: {}
      summary: Add tag
      tags:
      - Tag
  /v1/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: body of login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqLogin'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.UserAndTokenDto'
      summary: Login
      tags:
      - Login
swagger: "2.0"
