name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "main_server", "user_server", "category_server", "tag_server" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - name: Code Test
        run: go test -v -coverprofile=profile.cov ./...
      - name: Build and Push Docker Images
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker version
          echo "Logging in to Docker registry..."
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          
          # Determine the branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          
          # Build and push images based on the branch name
          if [ "$BRANCH_NAME" == "main" ] || [ "$BRANCH_NAME" == "main_server" ]; then
            docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog:latest
            docker push registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog:latest
          fi
          
          if [ "$BRANCH_NAME" == "user_server" ]; then
            docker build . --file ./user-server/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog-user-server:latest
            docker push registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog-user-server:latest
          fi
          
          if [ "$BRANCH_NAME" == "category_server" ]; then
            docker build . --file ./category-server/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog-category-server:latest
            docker push registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog-category-server:latest
          fi
          
          if [ "$BRANCH_NAME" == "tag_server" ]; then
            docker build . --file ./tag-server/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog-tag-server:latest
            docker push registry.cn-hangzhou.aliyuncs.com/vicblog/vicblog-tag-server:latest
          fi