name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # optional
          LANGUAGE: Chinese
          OPENAI_API_ENDPOINT: https://oneapi.gptnb.ai/v1
          MODEL: gpt-3.5-turbo # https://platform.openai.com/docs/models
          PROMPT: ${{ vars.PROMPT }}
          IGNORE_PATTERNS: /node_modules,*.md # Regex pattern to ignore files, separated by comma
